# Generated by Django 4.2.10 on 2024-03-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='درس')),
                ('section_of_study', models.CharField(max_length=30, verbose_name='مقطع تحصیلی')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.TextField(max_length=300, verbose_name='درجه سختی')),
                ('question', models.TextField(max_length=300, verbose_name='سوال')),
                ('option1', models.TextField(blank=True, max_length=300, null=True, verbose_name='گزینه 1')),
                ('option2', models.TextField(blank=True, max_length=300, null=True, verbose_name='گزینه 2')),
                ('option3', models.TextField(blank=True, max_length=300, null=True, verbose_name='گزینه 3')),
                ('option4', models.TextField(blank=True, max_length=300, null=True, verbose_name='گزینه 4')),
                ('answer', models.TextField(blank=True, max_length=300, null=True, verbose_name=' جواب')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.lesson')),
            ],
            options={
                'verbose_name': ' سوالات',
            },
        ),
    ]
