# Generated by Django 4.2.10 on 2024-03-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AducationaLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='مقطع تحصیلی')),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'مقاطع تحصیلی',
            },
        ),
        migrations.AlterModelOptions(
            name='questionsbank',
            options={'verbose_name': ' سوالات', 'verbose_name_plural': 'بانک سوالات'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_of_study',
        ),
        migrations.AddField(
            model_name='questionsbank',
            name='aducational_level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz_module.aducationalevel'),
            preserve_default=False,
        ),
    ]
