# Generated by Django 4.2.10 on 2024-03-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_module', '0002_aducationalevel_alter_questionsbank_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name=' قبول شده/نشده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='QuizDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز درس')),
                ('numbers_doing_exam', models.IntegerField(blank=True, null=True, verbose_name='دفعات شرکت در آزمون')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_module.lesson', verbose_name='درس')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.quizes')),
            ],
            options={
                'verbose_name': 'جزییات آزمون',
                'verbose_name_plural': 'جزییات آزمون ها',
            },
        ),
    ]
