# Generated by Django 4.2.10 on 2024-03-14 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_module', '0003_quizes_quizdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizes',
            new_name='Quiz',
        ),
    ]
