# Generated by Django 4.2.10 on 2024-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0004_rename_quizes_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdetail',
            name='numbers_doing_exam',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='دفعات شرکت در آزمون'),
        ),
    ]
