# Generated by Django 4.2.10 on 2024-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0006_alter_quizdetail_numbers_doing_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdetail',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز درس'),
        ),
    ]
