# Generated by Django 4.2.10 on 2024-03-16 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0007_alter_quizdetail_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 3, 15), verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
