# Generated by Django 4.2.10 on 2024-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0008_alter_quiz_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_finished',
            field=models.BooleanField(blank=True, null=True, verbose_name=' تمام شده/نشده'),
        ),
    ]
