# Generated by Django 4.2.10 on 2024-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0009_remove_quiz_is_passed_quiz_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='doing_exam',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
